### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/owendall/Library/Application Sup...

### ISSUE THREAD

**Issue by owendall** [atom/incompatible-packages#13]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [incompatible-packages](https://github.com/atom/incompatible-packages) package, v0.25.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at tryFile (module.js:105:22)
    at tryExtensions (module.js:115:20)
    at Function.Module._findPath (module.js:156:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/node_modules/incompatible-packages/node_modules/etch/dist/index.js:9:32)
    at Module._compile (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/node_modules/incompatible-packages/lib/status-icon-component.js:14:13)
    at Module._compile (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at createIcon (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/node_modules/incompatible-packages/lib/main.js:66:29)
    at /Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/node_modules/incompatible-packages/lib/main.js:53:18
    at Object.consumeStatusBar (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/node_modules/incompatible-packages/lib/main.js:61:7)
    at Provider.module.exports.Provider.provide (/Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Users/owendall/Library/Application Support/com.github.atom.ShipIt/update.x3Yj5PU/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "script-runner"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Pretty sure this has been fixed in the interim.
